### ISSUE TITLE
Issue with run_tcrmodel2_ub_tcr.py 

### ISSUE THREAD

**Issue by Ahmedalaraby20** [piercelab/tcrmodel2#2]
Hey there, 
I installed alphafold in a conda environment as suggested but every time i run `python run_tcrmodel2_ub_tcr.py`

I get the following 

```
Traceback (most recent call last):
  File "run_tcrmodel2_ub_tcr.py", line 222, in <module>
    app.run(main)
  File "/home/ahmedhas/anaconda3/envs/parafold/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/ahmedhas/anaconda3/envs/parafold/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "run_tcrmodel2_ub_tcr.py", line 55, in main
    tcra_seq=seq_utils.trim_tcr(tcra_seq)
  File "/home/ahmedhas/Desktop/tcrmodel2-main/scripts/seq_utils.py", line 26, in trim_tcr
    return parse_anarci(anarci_out)
  File "/home/ahmedhas/Desktop/tcrmodel2-main/scripts/seq_utils.py", line 17, in parse_anarci
    num=int(fields[1])
ValueError: invalid literal for int() with base 10: 'Unknown'

```

I run `which ANARCI`

and I get this `/home/ahmedhas/anaconda3/envs/parafold/bin/ANARCI`

I would love to your your website but I have loads for TCRs and it would be more easier for me to use it locally

**Comment by Ahmedalaraby20** [comment]
I ran it after adding the TCR seq but i am still facing some issues
```
/home/ahmedhas/anaconda3/envs/parafold/lib/python3.8/site-packages/Bio/Data/SCOPData.py:18: BiopythonDeprecationWarning: The 'Bio.Data.SCOPData' module will be deprecated in a future release of Biopython in favor of 'Bio.Data.PDBData.
  warnings.warn(
WARNING:root:Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
Traceback (most recent call last):
  File "run_alphafold_tcrmodel2.3.py", line 42, in <module>
    from alphafold.relax import relax
  File "/home/ahmedhas/Desktop/tcrmodel2-main/alphafold/relax/relax.py", line 18, in <module>
    from alphafold.relax import amber_minimize
  File "/home/ahmedhas/Desktop/tcrmodel2-main/alphafold/relax/amber_minimize.py", line 33, in <module>
    from simtk.openmm.app.internal.pdbstructure import PdbStructure
ModuleNotFoundError: No module named 'simtk.openmm.app.internal'
Traceback (most recent call last):
  File "run_tcrmodel2_ub_tcr.py", line 222, in <module>
    app.run(main)
  File "/home/ahmedhas/anaconda3/envs/parafold/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/ahmedhas/anaconda3/envs/parafold/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "run_tcrmodel2_ub_tcr.py", line 93, in main
    with open(pdb_fn) as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ahmedhas/Desktop/PILT/test/test/ranked_0.pdb'

```
there is a `Desktop/PILT/test/test/` but there is no `ranked_0.pdb`

I also ran `python -m openmm.testInstallation` and I got 

```
OpenMM Version: 7.7
Git Revision: 130124a3f9277b054ec40927360a6ad20c8f5fa6

There are 4 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Successfully computed forces
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
4 OpenCL - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 6.29603e-06
Reference vs. CUDA: 6.73526e-06
CPU vs. CUDA: 7.35615e-07
Reference vs. OpenCL: 6.74399e-06
CPU vs. OpenCL: 7.74033e-07
CUDA vs. OpenCL: 2.17201e-07

All differences are within tolerance.
 ```

**Comment by rui-yin** [comment]
Hi [Ahmedalaraby20](https://github.com/Ahmedalaraby20),

Thanks for your feedback and for trying to run locally! Good that you already got the ANARCI issue sorted out! Regarding the openMM, the version I have is: `7.5.1`. Maybe try this and see if it works?: 
`conda install -c conda-forge openmm=7.5.1`

Best,
Rui

**Comment by rui-yin** [comment]
Closing this issue for now. Please feel free to reopen if this is still a problem.
