### ISSUE TITLE
some error for type II mhc targets

### ISSUE THREAD

**Issue by ZhiYeG** [piercelab/tcrmodel2#7]
Hi, I got some other error while running your tool. Details shown bellow, please check it. Thanks in advance for your help.
The fasta file is:
>TCR_ALPHA
QQVRQSPQSLTVWEGETAILNCSYENSAFDYFPWYQQFPGEGPALLIAIRSVSDKKEDGRFTIFFNKREKKLSLHITDSQPGDSATYFCAASRDSGQKLVFGQGTILKVYLHIQNPDPAVYQLRDSKSSDKSVCLFTDFDSQTNVSQSKDSDVYITDKCVLDMRSMDFKSNSAVAWSNFACANAFNNSIIPEDTFFP
>TCR_BETA
AVTQSPRNKVAVTGGKVTLSCNQTNNHNNMYWYRQDTGHGLRLIHYSYGAGSTEKGDIPDGYKASRPSQENFSLILELATPSQTSVYFCASGDFWGDTLYFGAGTRLSVLEDLKNVFPPEVAVFEPSEAEISHTQKATLVCLATGFYPDHVELSWWVNGKEVHSGVCTDPQPLKEQPALNDSRYALSSRLRVSATFWQNPRNHFRCQVQFYGLSENDEWTQDRAKPVTQIVSAEAWGR
>PEPTIDE
FEAQKAKANKAVD
>MHC_ALPHA
IEADHVGTYGISVYQSPGDIGQYTFEFDGDELFYVDLDKKETVWMLPEFGQLASFDPQGGLQNIAVVKHNLGVLTKRSNSTPATNEAPQATVFPKSPVLLGQPNTLICFVDNIFPPVINITWLRNSKSVADGVYETSFFVNRDYSFHKLSYLTFIPSDDDIYDCKVEHWGLEEPVLKHW
>MHC_BETA
HFVYQFMGECYFTNGTQRIRYVTRYIYNREEYVRYDSDVGEHRAVTELGRPDAEYWNSQPEILERTRAELDTVCRHNYEGPETHTSLRRLEQPNVVISLSRTEALNHHNTLVCSVTDFYPAKIKVRWFRNGQEETVGVSSTQLIRNGDWTFQVLVMLEMTPRRGEVYTCHVEHPSLKSPITVEWRA
The error log is:
Traceback (most recent call last):
  File "run_alphafold_tcrmodel2.3.py", line 712, in <module>
    app.run(main)
  File "/hpc-cache-pfs/home/monomer/tools/tcrmodel2/env/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/hpc-cache-pfs/home/monomer/tools/tcrmodel2/env/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "run_alphafold_tcrmodel2.3.py", line 671, in main
    predict_structure(
  File "run_alphafold_tcrmodel2.3.py", line 269, in predict_structure
    feature_dict = data_pipeline.process(
  File "/hpc-cache-pfs/home/monomer/tools/tcrmodel2/alphafold/data/pipeline_multimer_custom_templates.py", line 350, in process
    chain_features = self._process_single_chain(
  File "/hpc-cache-pfs/home/monomer/tools/tcrmodel2/alphafold/data/pipeline_multimer_custom_templates.py", line 224, in _process_single_chain
    chain_features = self._monomer_data_pipeline.process(
  File "/hpc-cache-pfs/home/monomer/tools/tcrmodel2/alphafold/data/pipeline_custom_templates.py", line 396, in process
    template_features = create_single_template_features(
  File "/hpc-cache-pfs/home/monomer/tools/tcrmodel2/alphafold/data/custom_templates.py", line 151, in create_single_template_features
    identities = sum(target_sequence[i] == template_full_sequence[j]
  File "/hpc-cache-pfs/home/monomer/tools/tcrmodel2/alphafold/data/custom_templates.py", line 151, in <genexpr>
    identities = sum(target_sequence[i] == template_full_sequence[j]
IndexError: string index out of range
Traceback (most recent call last):
  File "/hpc-cache-pfs/home/monomer/tools/tcrmodel2//run_tcrmodel2.py", line 334, in <module>
    app.run(main)
  File "/hpc-cache-pfs/home/monomer/tools/tcrmodel2/env/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/hpc-cache-pfs/home/monomer/tools/tcrmodel2/env/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/hpc-cache-pfs/home/monomer/tools/tcrmodel2//run_tcrmodel2.py", line 236, in main
    with open("%s/%s_pmhc_oc/model_scores.txt" % (out_dir, job_id)) as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/hpc-cache-pfs/home/monomer/zhiye/tcr_model2/skempi/results_type/4P5T/4P5T_pmhc_oc/model_scores.txt'

**Comment by rui-yin** [comment]
Hi @ZhiYeG,

Thank you for bringing this to our attention. For class II TCR-pMHC complexes, our program is designed to handle peptide inputs that are 11 amino acids (aa) long: a 9 aa core with an additional 1 aa at both the N-terminal and C-terminal. If a peptide of different length is entered, the program will fail to create proper peptide-MHC templates. To align with the specification, you can use tools like NetMHCpan to identify the core sequence from your peptide. Once you have the core sequence, you can then extend it by 1 aa from both the N and C termini to get the 11-aa peptide. 

We've recognized the need for clarity and have updated the README file and added a peptide length check in the main Python script. If an incorrect length peptide is provided, an appropriate message will be displayed. We appreciate your feedback, which helps us improve the tool. Please let us know if you have any further questions or face any other issues.

Best,
Rui
